name: FromDoppler

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master", "INT"]
    tags:
      - v*.*.*

jobs:
  dotnet:
    name: Continuous Integration
    uses: FromDoppler/.github/.github/workflows/dotnet.yml@main
  nuget:
    if: ${{ github.event_name == 'push' }}
    name: Continuous Delivery
    uses: FromDoppler/.github/.github/workflows/continuous-delivery-nuget.yml@main
